sudo: false
language: python
python:
  - "3.5"
install:
  - pip install -r test_requirements.txt
  - python setup.py develop
script:
  py.test --cov=thebutton --cov-report=term --verbose
after_success:
  coveralls --verbose
